---
# tasks file for globodns
- name: install epel
  yum:
    name: epel-release
    state: present
  register: epel_installed

- name: install deps
  yum:
    name: "{{ globodns_packages }}"
    state: latest
  when: epel_installed is success
  register: dep_installed
