---
# tasks file for globodns
- name: Clone GloboDNS repo
  git:
    repo: "https://github.com/globocom/GloboDNS.git"
    dest: "{{ globodns_dstfolder }}"
  when: dep_installed is success
  register: deploy_sucess

- name: add ruby gpg keys
  shell: gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  register: gpg_key_fetched
  failed_when: gpg_key_fetched.rc != 0
  

- name: install ruby rvm
  shell: curl -sSL https://get.rvm.io | bash -s stable --ruby
  args:
    creates: /usr/bin/rvm

...
